import { OnboardingStep } from "../client/src/contexts/onboarding-context";

export const volunteerOnboardingSteps: OnboardingStep[] = [
  {
    id: "welcome",
    title: "Welcome to Synerxus!",
    description: "We're excited to have you join our global community of volunteers. This quick tour will show you how to discover opportunities, track your impact, and make a real difference in the world.",
    userType: "volunteer",
  },
  {
    id: "dashboard-kpis",
    title: "Your Impact at a Glance",
    description: "Your dashboard shows key metrics: hours logged, tasks completed, active projects, skills applied, and AIU (Annual Impact Units) earned. Tap any metric to see detailed breakdowns.",
    targetSelector: '[data-testid="kpi-hours"]',
    actions: ["Tap a KPI card to see details"],
    userType: "volunteer",
  },
  {
    id: "discover-opportunities",
    title: "Discover Volunteer Opportunities",
    description: "Find opportunities that match your skills and interests. Our AI-powered matching system suggests the best fits based on your profile, availability, and preferred SDG goals.",
    targetSelector: '[data-testid="nav-projects"]',
    actions: ["Browse available opportunities", "Apply to projects that interest you"],
    userType: "volunteer",
  },
  {
    id: "log-activity",
    title: "Log Your Volunteer Hours",
    description: "Track every contribution! Log your hours, describe your activities, and record the impact you've made. This data helps generate reports for organizations and funders.",
    targetSelector: '[data-testid="mobile-menu-trigger"]',
    actions: ["Open menu and select 'Log Activity'", "Enter hours and describe your work"],
    userType: "volunteer",
  },
  {
    id: "view-projects",
    title: "Your Active Projects",
    description: "See all projects you're assigned to. Each project card shows your role, hours contributed, upcoming tasks, and the SDG goals you're supporting.",
    targetSelector: '[data-testid="nav-projects"]',
    actions: ["View project details", "Check upcoming tasks"],
    userType: "volunteer",
  },
  {
    id: "track-impact",
    title: "Visualize Your Impact",
    description: "See beautiful charts showing your contributions over time, SDG alignment, skills utilized, and total people reached. Share your impact story with the world!",
    targetSelector: '[data-testid="nav-impact"]',
    actions: ["Explore your impact metrics", "Download your impact report"],
    userType: "volunteer",
  },
  {
    id: "manage-profile",
    title: "Complete Your Profile",
    description: "A complete profile helps organizations find you for relevant opportunities. Add your skills, availability, interests, and professional background.",
    targetSelector: '[data-testid="nav-profile"]',
    actions: ["Add your skills and interests", "Set your weekly availability", "Upload a profile photo"],
    userType: "volunteer",
  },
  {
    id: "messages",
    title: "Stay Connected",
    description: "Communicate with organizations and project coordinators directly through our messaging system. Get updates, ask questions, and coordinate with your team.",
    targetSelector: '[data-testid="btn-messages"]',
    actions: ["View your conversations", "Send messages to project leads"],
    userType: "volunteer",
  },
  {
    id: "sdg-alignment",
    title: "Support the UN SDGs",
    description: "Every hour you volunteer contributes to the UN Sustainable Development Goals. Track which SDGs you're supporting and how your efforts align with global impact objectives.",
    targetSelector: '[data-testid="kpi-sdgs"]',
    actions: ["See your SDG contributions", "Explore projects by SDG goal"],
    userType: "volunteer",
  },
  {
    id: "complete",
    title: "You're Ready to Make an Impact!",
    description: "Start exploring opportunities, logging your contributions, and tracking your global impact. Every hour counts toward building a better world. Welcome to the Synerxus community!",
    actions: ["Discover your first opportunity", "Complete your profile"],
    userType: "volunteer",
  },
];

export const organizationOnboardingSteps: OnboardingStep[] = [
  {
    id: "welcome",
    title: "Welcome to Synerxus!",
    description: "Your organization's command center for managing volunteers, tracking impact, and creating meaningful change. Let's set you up for success!",
    userType: "organization",
  },
  {
    id: "dashboard-overview",
    title: "Your Organization Dashboard",
    description: "Monitor everything at a glance: active volunteers, total hours contributed, project status, and SDG alignment. Use filters to view data by project, time period, or SDG goal.",
    targetSelector: '[data-testid="organization-dashboard"]',
    actions: ["Explore your KPI metrics", "Use filters to drill down into data"],
    userType: "organization",
  },
  {
    id: "quick-actions",
    title: "Quick Actions",
    description: "Create projects, invite volunteers, assign tasks, and generate reports with one click. These shortcuts help you manage your volunteer program efficiently.",
    targetSelector: '[data-testid="quick-action-create-project"]',
    actions: ["Create your first project", "Invite volunteers to join"],
    userType: "organization",
  },
  {
    id: "create-projects",
    title: "Create & Manage Projects",
    description: "Set up projects with clear goals, timelines, required skills, and SDG alignment. Define volunteer roles and track progress from start to completion.",
    targetSelector: '[data-testid="quick-action-create-project"]',
    actions: ["Create a new project", "Define roles and requirements", "Set SDG goals"],
    userType: "organization",
  },
  {
    id: "manage-volunteers",
    title: "Manage Your Volunteer Team",
    description: "View all volunteers assigned to your organization. See their skills, hours contributed, active projects, and performance metrics. Assign them to new projects or tasks.",
    targetSelector: '[data-testid="quick-action-invite-volunteer"]',
    actions: ["Browse your volunteer roster", "View individual contributor profiles", "Assign volunteers to projects"],
    userType: "organization",
  },
  {
    id: "create-tasks",
    title: "Assign Tasks to Volunteers",
    description: "Break down projects into manageable tasks. Assign tasks to volunteers, set deadlines, and track completion. Volunteers receive notifications for new assignments.",
    targetSelector: '[data-testid="quick-action-create-task"]',
    actions: ["Create tasks for projects", "Assign to specific volunteers", "Set due dates and priorities"],
    userType: "organization",
  },
  {
    id: "review-applications",
    title: "Review Volunteer Applications",
    description: "When volunteers apply to your opportunities, review their profiles, skills, and availability. Accept or decline applications and welcome new team members.",
    targetSelector: '[data-testid="button-view-all-applications"]',
    actions: ["Review pending applications", "Accept qualified volunteers", "Send welcome messages"],
    userType: "organization",
  },
  {
    id: "track-impact",
    title: "Track & Visualize Impact",
    description: "See real-time dashboards showing hours contributed, people reached, SDG progress, and project outcomes. Use data visualizations to understand your organization's impact.",
    targetSelector: '[data-testid="quick-action-view-reports"]',
    actions: ["View impact dashboards", "Analyze volunteer contributions", "Track SDG alignment"],
    userType: "organization",
  },
  {
    id: "generate-reports",
    title: "Generate Impact Reports",
    description: "Create professional impact reports for funders, stakeholders, and annual reviews. Export data as PDFs or CSVs. Use our AI-powered report generator for funder-ready documents.",
    targetSelector: '[data-testid="quick-action-view-reports"]',
    actions: ["Generate an impact report", "Export to PDF or CSV", "Share with stakeholders"],
    userType: "organization",
  },
  {
    id: "sdg-mapping",
    title: "SDG Goal Mapping",
    description: "Align your projects with UN Sustainable Development Goals. Track how volunteer hours contribute to each goal. Generate SDG-focused reports for impact disclosure.",
    targetSelector: '[data-testid="filter-sdg"]',
    actions: ["Map projects to SDG goals", "View SDG contribution breakdown"],
    userType: "organization",
  },
  {
    id: "notifications",
    title: "Stay Updated",
    description: "Receive notifications for new applications, task completions, milestone achievements, and important updates. Manage your notification preferences in settings.",
    targetSelector: '[data-testid="mobile-menu-notifications"]',
    actions: ["Check your notifications", "Respond to pending items"],
    userType: "organization",
  },
  {
    id: "complete",
    title: "You're All Set!",
    description: "Start creating projects, inviting volunteers, and tracking your organization's impact. Remember, you can restart this guide anytime from your profile settings. Let's make a difference together!",
    actions: ["Create your first project", "Invite volunteers", "Explore your dashboard"],
    userType: "organization",
  },
];

export const csrOnboardingSteps: OnboardingStep[] = [
  {
    id: "welcome",
    title: "Welcome to Synerxus CSR!",
    description: "Your corporate social responsibility command center. Track employee volunteering, measure impact, and demonstrate your company's commitment to sustainable development.",
    userType: "corporate-partner" as any,
  },
  {
    id: "dashboard-kpis",
    title: "CSR Key Performance Indicators",
    description: "Monitor real-time metrics: active employees volunteering, total hours contributed, economic value generated, and ROI on your CSR investment. Click any KPI for detailed breakdowns.",
    targetSelector: '[data-testid="kpi-total-hours"]',
    actions: ["Explore KPI details", "Track month-over-month progress"],
    userType: "corporate-partner" as any,
  },
  {
    id: "sdg-alignment",
    title: "SDG Impact Alignment",
    description: "See how your employee volunteer hours align with UN Sustainable Development Goals. Track contributions across all 17 SDGs and demonstrate your company's global impact.",
    targetSelector: '[data-testid="chart-sdg-alignment"]',
    actions: ["View SDG distribution", "Identify focus areas"],
    userType: "corporate-partner" as any,
  },
  {
    id: "employee-engagement",
    title: "Employee Engagement Funnel",
    description: "Track your employees' journey from signup to active volunteering to top performer status. Identify drop-off points and opportunities to boost participation rates.",
    targetSelector: '[data-testid="chart-employee-funnel"]',
    actions: ["Analyze funnel stages", "Identify disengaged employees", "Send engagement reminders"],
    userType: "corporate-partner" as any,
  },
  {
    id: "leaderboard",
    title: "Employee Leaderboard",
    description: "Recognize your top volunteer contributors. See who's leading in hours, projects, and impact. Use gamification to encourage friendly competition and increase engagement.",
    targetSelector: '[data-testid="csr-leaderboard"]',
    actions: ["View top performers", "Recognize achievements", "Award badges"],
    userType: "corporate-partner" as any,
  },
  {
    id: "geographic-map",
    title: "Geographic Impact Map",
    description: "Visualize where your employees are making a difference globally. See project locations, volunteer participation by region, and impact hotspots around the world.",
    targetSelector: '[data-testid="chart-geographic-impact"]',
    actions: ["Explore global impact", "Filter by region or country"],
    userType: "corporate-partner" as any,
  },
  {
    id: "project-sponsorship",
    title: "Project Sponsorship & ROI",
    description: "Track sponsored projects and calculate return on investment. See how your CSR budget translates into volunteer hours, community impact, and brand value.",
    targetSelector: '[data-testid="csr-roi-section"]',
    actions: ["View sponsored projects", "Calculate program ROI"],
    userType: "corporate-partner" as any,
  },
  {
    id: "compliance-scoring",
    title: "ESG & Compliance Scoring",
    description: "Track your readiness for sustainability reporting frameworks: B-Corp, GRI, ISO 26000, and SASB. Generate compliance-ready documentation for stakeholder reporting.",
    targetSelector: '[data-testid="csr-compliance-section"]',
    actions: ["Check compliance scores", "Identify improvement areas"],
    userType: "corporate-partner" as any,
  },
  {
    id: "impact-reports",
    title: "Generate CSR Impact Reports",
    description: "Create professional impact reports for stakeholders, investors, and annual sustainability disclosures. Export as branded PDFs with charts, metrics, and employee stories.",
    targetSelector: '[data-testid="nav-reports"]',
    actions: ["Generate a report", "Customize branding", "Export to PDF"],
    userType: "corporate-partner" as any,
  },
  {
    id: "challenges",
    title: "CSR Challenges & Goals",
    description: "Set company-wide volunteering goals and create challenges to boost engagement. Track progress toward annual CSR commitments and celebrate milestones.",
    targetSelector: '[data-testid="csr-challenges-section"]',
    actions: ["Create a challenge", "Set annual goals", "Track progress"],
    userType: "corporate-partner" as any,
  },
  {
    id: "employee-management",
    title: "Link & Manage Employees",
    description: "Connect your employee roster to track volunteer participation. Sync with HR systems, verify employee links, and manage department-level engagement metrics.",
    targetSelector: '[data-testid="csr-employees-section"]',
    actions: ["Link employees to your company", "Verify employee connections", "View by department"],
    userType: "corporate-partner" as any,
  },
  {
    id: "complete",
    title: "Ready to Drive CSR Impact!",
    description: "Start tracking your corporate volunteering program, engaging employees, and demonstrating your company's commitment to social responsibility. Restart this guide anytime from settings.",
    actions: ["Explore your dashboard", "Set CSR goals", "Generate your first report"],
    userType: "corporate-partner" as any,
  },
];
